import Foundation
import Supabase
import Combine
import Realtime

@MainActor
class ChatViewModel: ObservableObject {
    @Published var chats: [ChatRoom] = []
    @Published var messages: [ChatMessage] = []
    @Published var currentMessage: String = ""
    @Published var isLoading: Bool = false
    
    private let supabase = SupabaseManager.shared.client
    private var messageChannel: RealtimeChannelV2?
    
    // MARK: - Fetch Chat Rooms
    func fetchChatRooms(userId: UUID) async {
        isLoading = true
        defer { isLoading = false }
        
        do {
            // Join chat_participants with chat_rooms
            // We fetch participants for the user and include the room details
            // Supabase join query: "*, chat_rooms(*)"
            // Filter: user_id = userId
            // Order: chat_rooms(updated_at) DESC
            
            // Note: The models ChatRoom and ChatParticipant are already defined in ModelFile.swift
            // We need to fetch the rooms associated with the participants.
            
            let participants: [ChatParticipantWithRoom] = try await supabase
                .from("chat_participants")
                .select("*, chat_rooms(*)")
                .eq("user_id", value: userId)
                .execute()
                .value
            
            // Extract rooms from participants
            self.chats = participants.compactMap { $0.chatRoom }.sorted { ($0.updatedAt ?? Date.distantPast) > ($1.updatedAt ?? Date.distantPast) }
            
        } catch {
            print("Error fetching chat rooms: \(error)")
        }
    }
    
    // MARK: - Fetch Messages
    func fetchMessages(chatRoomId: UUID) async {
        isLoading = true
        defer { isLoading = false }
        
        do {
            let fetchedMessages: [ChatMessage] = try await supabase
                .from("chat_messages")
                .select()
                .eq("chat_room_id", value: chatRoomId)
                .order("created_at", ascending: true)
                .execute()
                .value
            
            self.messages = fetchedMessages
            
            // Subscribe to realtime updates for this room
            subscribeToMessages(chatRoomId: chatRoomId)
            
        } catch {
            print("Error fetching messages: \(error)")
        }
    }
    
    // MARK: - Send Message
    func sendMessage(chatRoomId: UUID, senderId: UUID) async {
        guard !currentMessage.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        
        let content = currentMessage
        currentMessage = "" // Clear input
        
        do {
            // Insert into chat_messages
            // UUID will be generated by Supabase if not provided
            let newMessage = ChatMessageInsert(
                chatRoomId: chatRoomId,
                senderId: senderId,
                messageType: .text,
                content: content
            )
            
            try await supabase
                .from("chat_messages")
                .insert(newMessage)
                .execute()
            
            // Note: The message will be appended via realtime subscription
            
        } catch {
            print("Error sending message: \(error)")
            // Restore message if failed?
            currentMessage = content
        }
    }
    
    // MARK: - Realtime Subscription
    func subscribeToMessages(chatRoomId: UUID) {
        if let currentChannel = messageChannel {
            Task {
                await supabase.removeChannel(currentChannel)
            }
        }
        
        let channel = supabase.channel("chat-\(chatRoomId.uuidString)")
        
        channel.on(
            RealtimeChannelV2.PostgresChangeEvent.insert,
            schema: "public",
            table: "chat_messages"
        ) { [weak self] payload in
            guard let self = self else { return }
            
            Task { @MainActor in
                do {
                    if let data = try? JSONSerialization.data(withJSONObject: payload.record) {
                        
                        let decoder = JSONDecoder()
                        decoder.dateDecodingStrategy = .iso8601
                        
                        let newMessage = try decoder.decode(ChatMessage.self, from: data)
                        
                        if newMessage.chatRoomId == chatRoomId &&
                           !self.messages.contains(where: { $0.id == newMessage.id }) {
                            self.messages.append(newMessage)
                        }
                    }
                } catch {
                    print("Realtime decode error:", error)
                }
            }
        }
        
        self.messageChannel = channel
        
        Task {
            await channel.subscribe()
        }
    }
    
    deinit {
        if let channel = messageChannel {
            // Since we can't await in deinit, we use a global task
            Task {
                // supabase.removeChannel(channel)
            }
        }
    }
}

// MARK: - Helper Models for Decoding
struct ChatParticipantWithRoom: Codable {
    let chatRoomId: UUID
    let userId: UUID
    let joinedAt: Date?
    let lastReadAt: Date?
    let chatRoom: ChatRoom?
    
    enum CodingKeys: String, CodingKey {
        case chatRoomId = "chat_room_id"
        case userId = "user_id"
        case joinedAt = "joined_at"
        case lastReadAt = "last_read_at"
        case chatRoom = "chat_rooms"
    }
}

struct ChatMessageInsert: Codable {
    var chatRoomId: UUID
    var senderId: UUID
    var messageType: MessageType
    var content: String
    
    enum CodingKeys: String, CodingKey {
        case chatRoomId = "chat_room_id"
        case senderId = "sender_id"
        case messageType = "message_type"
        case content
    }
}

extension ChatMessage: Equatable {
    public static func == (lhs: ChatMessage, rhs: ChatMessage) -> Bool {
        lhs.id == rhs.id
    }
}
